the-gossip-project/config/routes.rb
Rails.application.routes.draw do

	root 'gossips#index'

	get 'gossips/new'

	get 'gossips/show'

	get 'gossips/edit'

	resources :gossips
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

the-gossip-project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

the-gossip-project/app/models/gossip.rb
class Gossip < ApplicationRecord
end

the-gossip-project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

the-gossip-project/app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

	def index

		@gossip = Gossip.all

	end

	def show

		@gossip = Gossip.find(params[:id])

	end

	def update

		@gossip = Gossip.find(params[:id])

		@gossip.update(gossip_params)

		redirect_to gossip_path(@gossip.id)

	end

	def destroy

		@gossip = Gossip.find(params[:id])

		@gossip.destroy

		redirect_to gossips_path

	end

	def new

		@gossip = Gossip.new

	end

	def create

		@gossip = Gossip.create(gossip_params)

		redirect_to gossip_path(@gossip.id)
  	
	end

	def edit

		@gossip = Gossip.find(params[:id])

	end

	private

	def gossip_params

		params.require(:gossip).permit(:anonymous_author, :content)

	end

end

the-gossip-project/app/helpers/application_helper.rb
module ApplicationHelper
end

the-gossip-project/app/helpers/gossips_helper.rb
module GossipsHelper
end

the-gossip-project/app/views/gossips/edit.html.erb
<h1>Editer le gossip</h1>

 <%= form_for @gossip do |f| %>

   <div>

      <label>Vous êtes ?</label>

      <%= f.text_field :anonymous_author %>

   </div>

   <div>

      <label>Contenu du gossip</label>

      <%= f.text_area :content %>

   </div>

   <div>

      <button type="submit" >Editer le gossip</button>

   </div>

   <%= link_to 'Clique pour détruire', @gossip, method: :delete %>

 <% end %>

the-gossip-project/app/views/gossips/index.html.erb
<h1>Gossips</h1>

<% @gossip.each do |gossip| %>

	<h1><%= gossip.anonymous_author %></h1>

	<p><%= gossip.content %></p>

	<a href="<%= gossip_path(gossip.id) %>" data-method="delete" >Supprimer</a>

<% end %>

<p>

	<a href="<%= new_gossip_path %>" >Créer un gossip</a>

</p>

the-gossip-project/app/views/gossips/new.html.erb
<h1>Créer un gossip</h1>

 <%= form_for @gossip do |f| %>

   <div>

   	<label>Vous êtes ?</label>

   	<%= f.text_field :anonymous_author %>

   </div>

   <div>

   	<label>Contenu du gossip</label>

   	<%= f.text_area :content %>

   </div>

   <div>

   	<button type="submit" >Créer un gossip</button>

   </div>

 <% end %>

the-gossip-project/app/views/gossips/show.html.erb
<h1><%= @gossip.anonymous_author %></h1>


<p><%= @gossip.content %></p>

<p>

	<a href="<%= edit_gossip_path(@gossip.id) %>" >éditer le gossip</a>

</p>

<p>

	<a href="<%= gossips_path %>" >revenir aux gossips</a>

</p>

the-gossip-project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>